"""YOLO segmentation-based mango surface defect detector."""

from pathlib import Path
from typing import Dict, Optional

import cv2
import numpy as np
from ultralytics import YOLO


PROJECT_ROOT = Path(__file__).resolve().parent.parent

DEFAULT_MODEL_PATH = (
    PROJECT_ROOT
    / "models"
    / "mango_defect_seg.pt"
)


class BlemishDetector:
    """
    Mango surface-defect segmentation using the trained YOLO model.

    Current trained dataset:
        class 0 = defect

    IMPORTANT:
    The current model does NOT distinguish separate:
        - blemish
        - bruise
        - scratch
        - physical damage

    Therefore:
        defect_percentage = actual YOLO segmented defect %
        blemish_percentage = same as total defect %
        damage_percentage = 0.0

    A future 2-class model can separate blemish and damage.
    """

    def __init__(
        self,
        model_path: str | Path = DEFAULT_MODEL_PATH,
        confidence_threshold: float = 0.25,
        iou_threshold: float = 0.50,
        image_size: int = 640,
        mask_threshold: float = 0.50,
    ):
        self.model_path = Path(model_path)

        self.confidence_threshold = float(
            confidence_threshold
        )

        self.iou_threshold = float(
            iou_threshold
        )

        self.image_size = int(
            image_size
        )

        self.mask_threshold = float(
            mask_threshold
        )

        if not self.model_path.exists():
            raise FileNotFoundError(
                "Trained mango defect segmentation model "
                f"was not found:\n{self.model_path}"
            )

        self.model = YOLO(
            str(self.model_path)
        )

    # ================================================================
    # MAIN ANALYSIS
    # ================================================================

    def analyze(
        self,
        image: np.ndarray,
        mango_mask: Optional[np.ndarray] = None,
        ripeness_label: Optional[str] = None,
    ) -> Dict:
        """
        Analyse visible mango surface defects.

        Parameters
        ----------
        image:
            BGR OpenCV image of one mango crop.

        mango_mask:
            Binary mango mask generated by the preprocessing pipeline.

        ripeness_label:
            Kept only for compatibility.
            Ripeness is NOT used to decide whether something is a defect.
        """

        if image is None:
            raise ValueError(
                "Input mango image is None."
            )

        if (
            image.ndim != 3
            or image.shape[2] != 3
        ):
            raise ValueError(
                "Input image must be a BGR image "
                "with shape (H, W, 3)."
            )

        image = image.copy()

        height, width = image.shape[:2]

        # ============================================================
        # PREPARE MANGO MASK
        # ============================================================

        if mango_mask is None:

            safe_mango_mask = np.full(
                (height, width),
                255,
                dtype=np.uint8,
            )

        else:

            if mango_mask.shape[:2] != (
                height,
                width,
            ):
                mango_mask = cv2.resize(
                    mango_mask,
                    (width, height),
                    interpolation=cv2.INTER_NEAREST,
                )

            safe_mango_mask = np.where(
                mango_mask > 0,
                255,
                0,
            ).astype(np.uint8)

        # Slightly remove the outside edge.
        #
        # This helps prevent background pixels or mango-outline
        # artefacts from being counted as defects.

        mango_area_before = cv2.countNonZero(
            safe_mango_mask
        )

        if mango_area_before > 0:

            kernel_size = max(
                3,
                int(
                    round(
                        min(
                            height,
                            width,
                        )
                        * 0.008
                    )
                ),
            )

            if kernel_size % 2 == 0:
                kernel_size += 1

            kernel = cv2.getStructuringElement(
                cv2.MORPH_ELLIPSE,
                (
                    kernel_size,
                    kernel_size,
                ),
            )

            eroded = cv2.erode(
                safe_mango_mask,
                kernel,
                iterations=1,
            )

            # Do not use an erosion result that
            # accidentally removes almost everything.
            if cv2.countNonZero(eroded) > 0:

                safe_mango_mask = eroded

        mango_pixel_area = int(
            cv2.countNonZero(
                safe_mango_mask
            )
        )

        # ============================================================
        # EMPTY MASK
        # ============================================================

        if mango_pixel_area == 0:

            return self._empty_result(
                image=image,
                mango_mask=safe_mango_mask,
            )

        # ============================================================
        # YOLO SEGMENTATION
        # ============================================================

        results = self.model.predict(
            source=image,
            conf=self.confidence_threshold,
            iou=self.iou_threshold,
            imgsz=self.image_size,
            retina_masks=True,
            verbose=False,
        )

        defect_mask = np.zeros(
            (height, width),
            dtype=np.uint8,
        )

        components = []

        # ============================================================
        # READ PREDICTED INSTANCE MASKS
        # ============================================================

        if results:

            result = results[0]

            if (
                result.masks is not None
                and result.boxes is not None
                and len(result.boxes) > 0
            ):

                predicted_masks = (
                    result.masks.data
                    .cpu()
                    .numpy()
                )

                boxes = result.boxes

                for index, predicted_mask in enumerate(
                    predicted_masks
                ):

                    # ------------------------------------------------
                    # Resize mask to actual mango crop
                    # ------------------------------------------------

                    if predicted_mask.shape[:2] != (
                        height,
                        width,
                    ):

                        predicted_mask = cv2.resize(
                            predicted_mask,
                            (
                                width,
                                height,
                            ),
                            interpolation=cv2.INTER_LINEAR,
                        )

                    instance_mask = np.where(
                        predicted_mask
                        >= self.mask_threshold,
                        255,
                        0,
                    ).astype(np.uint8)

                    # ------------------------------------------------
                    # Keep only pixels on the mango
                    # ------------------------------------------------

                    instance_mask = cv2.bitwise_and(
                        instance_mask,
                        safe_mango_mask,
                    )

                    instance_area = int(
                        cv2.countNonZero(
                            instance_mask
                        )
                    )

                    if instance_area <= 0:
                        continue

                    # ------------------------------------------------
                    # Confidence
                    # ------------------------------------------------

                    confidence = float(
                        boxes.conf[index]
                    )

                    # ------------------------------------------------
                    # Class
                    # ------------------------------------------------

                    class_id = int(
                        boxes.cls[index]
                    )

                    class_name = (
                        result.names.get(
                            class_id,
                            "defect",
                        )
                    )

                    # ------------------------------------------------
                    # Bounding box
                    # ------------------------------------------------

                    x1, y1, x2, y2 = map(
                        int,
                        boxes.xyxy[
                            index
                        ].tolist(),
                    )

                    # ------------------------------------------------
                    # Combine this mask with all defects
                    # ------------------------------------------------

                    defect_mask = np.maximum(
                        defect_mask,
                        instance_mask,
                    )

                    # ------------------------------------------------
                    # Component information
                    # ------------------------------------------------

                    components.append(
                        {
                            "class_id": class_id,
                            "type": class_name,
                            "class_name": class_name,
                            "confidence": confidence,
                            "area": instance_area,
                            "pixel_area": instance_area,
                            "bbox": (
                                x1,
                                y1,
                                x2,
                                y2,
                            ),
                        }
                    )

        # ============================================================
        # FINAL MASK IS RESTRICTED TO MANGO
        # ============================================================

        defect_mask = cv2.bitwise_and(
            defect_mask,
            safe_mango_mask,
        )

        defect_pixel_area = int(
            cv2.countNonZero(
                defect_mask
            )
        )

        # ============================================================
        # DEFECT PERCENTAGE
        # ============================================================

        if mango_pixel_area > 0:

            defect_percentage = (
                defect_pixel_area
                / mango_pixel_area
                * 100.0
            )

        else:

            defect_percentage = 0.0

        # Never allow strange numerical values.
        defect_percentage = max(
            0.0,
            min(
                100.0,
                defect_percentage,
            ),
        )

        # ============================================================
        # SEVERITY
        # ============================================================

        if defect_percentage < 1.5:

            severity = "Low"

        elif defect_percentage < 5.0:

            severity = "Medium"

        else:

            severity = "High"

        # ============================================================
        # DEFECT TYPE
        # ============================================================

        if defect_pixel_area > 0:

            defect_types = [
                "Surface Defect"
            ]

        else:

            defect_types = [
                "None"
            ]

        # ============================================================
        # OVERLAY
        # ============================================================

        overlay = image.copy()

        red_overlay = image.copy()

        red_overlay[
            defect_mask > 0
        ] = (
            0,
            0,
            255,
        )

        overlay = cv2.addWeighted(
            image,
            0.72,
            red_overlay,
            0.28,
            0,
        )

        contours, _ = cv2.findContours(
            defect_mask,
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE,
        )

        cv2.drawContours(
            overlay,
            contours,
            -1,
            (
                0,
                0,
                255,
            ),
            1,
        )

        # ============================================================
        # COMPATIBILITY MASKS
        #
        # Your existing assessment pipeline expects these fields.
        #
        # Since this model has one class only:
        #
        # dark_spots -> all segmented defects
        # brown_lesions -> empty
        # severe_dark -> empty
        # wet_damage -> empty
        # scratch_mask -> empty
        # white_surface -> empty
        #
        # This means total defect = blemish coverage for now.
        # ============================================================

        empty_mask = np.zeros(
            (
                height,
                width,
            ),
            dtype=np.uint8,
        )

        return {
            # --------------------------------------------------------
            # Main results
            # --------------------------------------------------------

            "defect_percentage": round(
                float(
                    defect_percentage
                ),
                2,
            ),

            "blemish_percentage": round(
                float(
                    defect_percentage
                ),
                2,
            ),

            "damage_percentage": 0.0,

            "defect_pixel_area": (
                defect_pixel_area
            ),

            "blemish_pixel_area": (
                defect_pixel_area
            ),

            "damage_pixel_area": 0,

            "mango_pixel_area": (
                mango_pixel_area
            ),

            "severity": severity,

            "grade": "Unavailable",

            "defect_types": (
                defect_types
            ),

            "component_count": len(
                components
            ),

            "components": components,

            # --------------------------------------------------------
            # Masks
            # --------------------------------------------------------

            "damage_mask": defect_mask,

            "defect_mask": defect_mask,

            "blemish_mask": defect_mask,

            "damage_only_mask": (
                empty_mask.copy()
            ),

            "safe_mango_mask": (
                safe_mango_mask
            ),

            # --------------------------------------------------------
            # Compatibility fields expected by old code
            # --------------------------------------------------------

            "blackhat": (
                empty_mask.copy()
            ),

            "candidate_mask": (
                defect_mask.copy()
            ),

            "dark_spots": (
                defect_mask.copy()
            ),

            "brown_lesions": (
                empty_mask.copy()
            ),

            "severe_dark": (
                empty_mask.copy()
            ),

            "wet_damage": (
                empty_mask.copy()
            ),

            "scratch_mask": (
                empty_mask.copy()
            ),

            "white_surface": (
                empty_mask.copy()
            ),

            # --------------------------------------------------------
            # Visual output
            # --------------------------------------------------------

            "overlay": overlay,

            # --------------------------------------------------------
            # Model information
            # --------------------------------------------------------

            "model_path": str(
                self.model_path
            ),

            "confidence_threshold": (
                self.confidence_threshold
            ),

            "iou_threshold": (
                self.iou_threshold
            ),

            "image_size": (
                self.image_size
            ),

            "mask_threshold": (
                self.mask_threshold
            ),
        }

    # ================================================================
    # EMPTY RESULT
    # ================================================================

    def _empty_result(
        self,
        image: np.ndarray,
        mango_mask: np.ndarray,
    ) -> Dict:

        height, width = image.shape[:2]

        empty_mask = np.zeros(
            (
                height,
                width,
            ),
            dtype=np.uint8,
        )

        return {
            "defect_percentage": 0.0,
            "blemish_percentage": 0.0,
            "damage_percentage": 0.0,

            "defect_pixel_area": 0,
            "blemish_pixel_area": 0,
            "damage_pixel_area": 0,

            "mango_pixel_area": int(
                cv2.countNonZero(
                    mango_mask
                )
            ),

            "severity": "Low",

            "grade": "Unavailable",

            "defect_types": [
                "None"
            ],

            "component_count": 0,

            "components": [],

            "damage_mask": (
                empty_mask.copy()
            ),

            "defect_mask": (
                empty_mask.copy()
            ),

            "blemish_mask": (
                empty_mask.copy()
            ),

            "damage_only_mask": (
                empty_mask.copy()
            ),

            "safe_mango_mask": (
                mango_mask.copy()
            ),

            "blackhat": (
                empty_mask.copy()
            ),

            "candidate_mask": (
                empty_mask.copy()
            ),

            "dark_spots": (
                empty_mask.copy()
            ),

            "brown_lesions": (
                empty_mask.copy()
            ),

            "severe_dark": (
                empty_mask.copy()
            ),

            "wet_damage": (
                empty_mask.copy()
            ),

            "scratch_mask": (
                empty_mask.copy()
            ),

            "white_surface": (
                empty_mask.copy()
            ),

            "overlay": image.copy(),

            "model_path": str(
                self.model_path
            ),

            "confidence_threshold": (
                self.confidence_threshold
            ),

            "iou_threshold": (
                self.iou_threshold
            ),

            "image_size": (
                self.image_size
            ),

            "mask_threshold": (
                self.mask_threshold
            ),
        }